### ISSUE TITLE
User can choose a Sol (day on Mars)from 1-1653 and select a camera (front, rear, or mast) #1

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose a Sol (day on Mars)from 1-1653 and select a camera (front, rear, or mast)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is presented with a form that asks them which sol they want to see an image from a specific camera

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/201742887-1107581c-2183-410d-8ad1-429f7c644a54.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add an orange header
- [x] create view swappable body
- [x] add form to the body
- [x] listen for submit on the form
- [x] push data from form into new object
- [x] send request to https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos with info from new obj
- [x] create event listener for the http request
- [x] from the result obj from API, retrieve earth_date and img_src and place in obj
- [x] console log the obj
