### ISSUE TITLE
User can view a mars pic corresponding to their mission day and cam choice #2

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a mars pic corresponding to their mission day and cam choice

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user is presented a new view of the preview of an image if there was one returned for their day and camera choice. They will be presented with an option to add the image to their collection or simply to return to the previous screen to make a new request with new parameters. If there was not an image returned for their selections, then the user is notified.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/202008749-1870a22b-631b-443d-93bd-1b3945ed0244.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create new view swap page
- [x] display image in center of page
- [x] add a back button
- [x] add save button
- [x] display sol chosen by user
- [x] display corresponding earth date
- [x] make sure the page is viewable nicely on both mobile and desktop
- [x] create error handling for when arguments dont return anything
