### ISSUE TITLE
User can add their photo to their collection #3

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add the previewed photo to their collection

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click the Add+ button to add the photo to their collection and immediately be taken to the collection view to see the photo with any other previously added ones

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/202082311-89af5a62-b474-48fd-884c-d336b57974fa.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create event listener for the add button
- [x] create a data model
- [x] make sure the photo being added receives the next entry ID
- [x] upon click of add, hide the image view page
- [x] create collection view page and make sure that it unhides on add
- [x] set up local storage and make sure its being saved on unload
