### ISSUE TITLE
User can view their photo collection #4

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can see their collection of photos

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

upon click of the add button, preview is hidden and collection is displayed in a 3 column grid

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/202312059-eef4124e-3d67-4312-9ba4-884b649607b6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create header element for the column view
- [x] create parent element for rendered items to be added to
- [x] add logo to replace mars explorer text in header
- [x] click logo to view entries
- [x] update figma with the view button + text alignment
- [x] create the renderEntry function
- [x] render each pic as list item in unordered list
- [x] make flex basis 100% / 3 to have list be 3 col grid
- [x] ensure flex is set to wrap
- [x] make each image have max-width and max-height
