### ISSUE TITLE
User can delete a photo #5

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a photo from the collection 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

with a single click of a red x icon displayed in the top right corner of each photo added to their collection, a user will be able to easily remove that image to make some room for more

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/202771362-9e436c9f-a1af-4625-8f79-0fcc3536947d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] modify renderEntry function to make the image area relative
- [x] add icon i creation with relative top corner positioning
- [x] create eventlistener for the parent UL
- [x] filter out clicks that arent on the specific i element
